version: "2"
services:
  node:
    build: ./docker
    volumes:
      # ADJUST: path to the building navigator
      - ../building-navigator:/usr/src/app
    ports:
      - 8080:8080
    links:
      - db:db
      #- fuseki:fuseki
    command: >
      sh -c "npm install &&
      webpack-dev-server \
        --config webpack.config.js \
        --host 0.0.0.0 \
        --port 8080 \
        --mode development"

  db:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.4
    environment:
        SPARQL_UPDATE: "true"
        DEFAULT_GRAPH: "https://opendata.leipzig.de/bvlplaces/"
    volumes:
        # ADJUST: path to the data dump to import some data
        - ./data/import:/data/toLoad
        # folder to virtuosos db (uncomment for persistance)
        # - ./data/virtuoso:/data
    ports:
        - 8890:8890

  #fuseki:
  #  image: stain/jena-fuseki
  #  ports:
  #      - 3030:3030
